version: "2"

services:
  mongo:
    container_name: ms_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/db:/data/db"

  nginx:
    build: ./nginx
    container_name: ms_nginx
    depends_on:
      - users
    ports:
      - "80:80"

  users:
    build: ./users
    container_name: ms_users
    env_file:
      - .env
    environment:
      - loglevel = none
      - PORT = process.env.PORT
      - MONGODB_URI = process.env.MONGODB_URI
    volumes:
      - "./users:/src/app"
    working_dir: "/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm run dev
