version: "2"

services:
  mongo:
    container_name: ms_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/db:/data/db"

  nginx:
    build: ./nginx
    container_name: ms_nginx
    depends_on:
      - users
      - products
      - shopping
    ports:
      - "80:80"

  users:
    build: ./users
    container_name: ms_users
    env_file:
      - .env
    environment:
      - loglevel = none
      - PORT = process.env.PORT
      - MONGODB_URI = process.env.MONGODB_URI
    volumes:
      - "./users:/src/app"
    working_dir: "/src/app"
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  products:
    build: ./products
    container_name: ms_products
    env_file:
      - .env
    environment:
      - loglevel = none
      - PORT = process.env.PORT
      - MONGODB_URI = process.env.MONGODB_URI
    volumes:
      - "./products:/src/app"
    working_dir: "/src/app"
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  shopping:
    build: ./shopping
    container_name: ms_shopping
    env_file:
      - .env
    environment:
      - loglevel = none
      - PORT = process.env.PORT
      - MONGODB_URI = process.env.MONGODB_URI
    volumes:
      - "./shopping:/src/app"
    working_dir: "/src/app"
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - mongo
